/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

type SetupRef struct {
	ReferenceID int    `json:"referenceID,omitempty"`
	Name        string `json:"name,omitempty"`
	Type_       string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	FolderPath  string `json:"folderPath,omitempty"`
}
