/*
 * JAMS REST API

 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

import (
	"time"
)

type BatchQueue struct {
	QueueID       int         `json:"queueID,omitempty"`
	QueueName     string      `json:"queueName,omitempty"`
	Description   string      `json:"description,omitempty"`
	JobCount      int         `json:"jobCount,omitempty"`
	JobLimit      int         `json:"jobLimit,omitempty"`
	LastChangeUTC time.Time   `json:"lastChangeUTC,omitempty"`
	LastChangedBy string      `json:"lastChangedBy,omitempty"`
	Started       bool        `json:"started,omitempty"`
	StartedOn     []QueueNode `json:"startedOn,omitempty"`
}
