/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RangeVariable struct {
	Name string `json:"name,omitempty"`
	TypeReference *IEdmTypeReference `json:"typeReference,omitempty"`
	Kind int32 `json:"kind,omitempty"`
}
