/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ODataQueryContext struct {
	Model *IEdmModel `json:"model,omitempty"`
	ElementType *IEdmType `json:"elementType,omitempty"`
	NavigationSource *IEdmNavigationSource `json:"navigationSource,omitempty"`
	ElementClrType string `json:"elementClrType,omitempty"`
	Path *ODataPath `json:"path,omitempty"`
}
