/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

import (
	"time"
)

type Dependency struct {
	DependencyName string    `json:"dependencyName,omitempty"`
	DependencyType string    `json:"dependencyType,omitempty"`
	DependID       int32     `json:"dependID,omitempty"`
	Description    string    `json:"description,omitempty"`
	LastChangeUTC  time.Time `json:"lastChangeUTC,omitempty"`
}
