/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IEdmStructuralProperty struct {
	DefaultValueString string `json:"defaultValueString,omitempty"`
	ConcurrencyMode string `json:"concurrencyMode,omitempty"`
}
