/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TriggerAction struct {
	ActionID int32 `json:"actionID,omitempty"`
	ActionName string `json:"actionName,omitempty"`
	LastChangeUTC time.Time `json:"lastChangeUTC,omitempty"`
	Description string `json:"description,omitempty"`
	ActionType string `json:"actionType,omitempty"`
}
