/*
 * JAMS REST API

 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

import (
	"time"
)

type Trigger struct {
	TriggerID        int             `json:"triggerID,omitempty"`
	TriggerName      string          `json:"triggerName,omitempty"`
	QualifiedName    string          `json:"qualifiedName,omitempty"`
	Description      string          `json:"description,omitempty"`
	ParentFolderID   int             `json:"parentFolderID,omitempty"`
	ParentFolderName string          `json:"parentFolderName,omitempty"`
	Status           string          `json:"status,omitempty"`
	UserName         string          `json:"userName,omitempty"`
	ResetWhenFired   bool            `json:"resetWhenFired,omitempty"`
	LastChangeUTC    time.Time       `json:"lastChangeUTC,omitempty"`
	LastResetUTC     time.Time       `json:"lastResetUTC,omitempty"`
	LastFiredUTC     time.Time       `json:"lastFiredUTC,omitempty"`
	Events           []TriggerEvent  `json:"events,omitempty"`
	Actions          []TriggerAction `json:"actions,omitempty"`
}
