/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

type OrderByClause struct {
	ThenBy        *OrderByClause     `json:"thenBy,omitempty"`
	Expression    *SingleValueNode   `json:"expression,omitempty"`
	Direction     string             `json:"direction,omitempty"`
	RangeVariable *RangeVariable     `json:"rangeVariable,omitempty"`
	ItemType      *IEdmTypeReference `json:"itemType,omitempty"`
}
