/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

type FilterQueryOption struct {
	Context      *ODataQueryContext    `json:"context,omitempty"`
	Validator    *FilterQueryValidator `json:"validator,omitempty"`
	FilterClause *FilterClause         `json:"filterClause,omitempty"`
	RawValue     string                `json:"rawValue,omitempty"`
}
