/*
 * JAMS REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: V6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jams

type IEdmModel struct {
	SchemaElements                []IEdmSchemaElement                `json:"schemaElements,omitempty"`
	VocabularyAnnotations         []IEdmVocabularyAnnotation         `json:"vocabularyAnnotations,omitempty"`
	ReferencedModels              []IEdmModel                        `json:"referencedModels,omitempty"`
	DeclaredNamespaces            []string                           `json:"declaredNamespaces,omitempty"`
	DirectValueAnnotationsManager *IEdmDirectValueAnnotationsManager `json:"directValueAnnotationsManager,omitempty"`
	EntityContainer               *IEdmEntityContainer               `json:"entityContainer,omitempty"`
}
